mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),

    path('enquete/<int:pk>',
        views.DetalhesView.as_view(), name = 'detalhes'
        ),

    path('enquete/<int:pk>/resultado',
        views.ResultadoView.as_view(), name = 'resultado'
        ),

    path('enquete/<int:id_enquete>/votacao',
        views.votacao, name = 'votacao'
        ),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
class Pergunta(models.Model):
    texto = models.CharField(max_length=200)
    data_de_publicacao = models.DateTimeField('Data de publicação')
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_de_publicacao <= agora

class Opcao(models.Model):
    texto = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Pergunta, Opcao



class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'ultimas_perguntas'
    def get_queryset(self):
        return Pergunta.objects.filter(data_de_publicacao__lte=timezone.now()
        ).order_by('-data_de_publicacao')[:5]

class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'polls/detalhes.html'
    def get_queryset(self):
        return Pergunta.objects.filter(data_de_publicacao__lte = timezone.now())


class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'polls/resultado.html'

def votacao (request, id_enquete):
    pergunta = get_object_or_404(Pergunta, pk = id_enquete)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        return render(request, 'polls/detalhes.html',{
            'pergunta' : pergunta,
            'error_message' : "Selecione uma opção VÁLIDA!"
            })
    else:
        opcao_selecionada.votos +=1
        opcao_selecionada.save()
        return HttpResponseRedirect(
            reverse('polls:resultado', args=(pergunta.id,))
            )

mysite/polls/templates/polls/detalhes.html
<html>
    <head>
        <title>App enquete</title>
    </head>
    <body>
        <h1>Detalhes da Enquete {{ pergunta.id }}</h1>
        <u>Pergunta:</u> {{ pergunta.texto }}<br/>
        <u>Data de publicação</u>: {{ pergunta.data_de_publicacao }}
        {% if error_message %}
            <hr>
            <strong>{{ error_message }}</strong>
        {% endif %}
        <form action="{% url 'polls:votacao' pergunta.id %}" method = "post">
            {% csrf_token %}


        <ul>
            {% for opcao in pergunta.opcao_set.all%}
                <li> <input type = "radio" name="opcao"
                    id = "opcao{{ forloop.counter}}" value = "{{opcao.id}}"
                    <label for="opcao{{ forloop.counter }}">
                        {{opcao.texto}}"
                    </label>
                </li>
            {% endfor %}

        </ul>
        <input type="submit" value= "Registre o seu voto">
        </form>
    </body>

</html>

mysite/polls/templates/polls/index.html
<html>
    <head>
        <title>App enquete</title>
    </head>
    <body>
        {% if ultimas_perguntas %}
            <h2>Lista das últimas enquetes</h2>
            <ul>
                {% for pergunta in ultimas_perguntas %}
                    <li><a href="{% url 'polls:detalhes' pergunta.id %}">
                        {{ pergunta.texto }}
                    </a></li>
                {% endfor %}
            </ul>
        {% else %}
            <h3>Não há enquetes cadastradas até o momento!</h3>

        {% endif %}
    </body>
</html>

mysite/polls/templates/polls/resultado.html
<html>
    <head>
        <title>App enquete</title>
    </head>
    <body>
        <h2>Resultado parcial da Enquete {{ pergunta.id }}</h2>
        <u>Pergunta:</u> {{ pergunta.texto }}<br/>
        <u>Data de publicação</u>: {{ pergunta.data_de_publicacao }}
        <ul>
            {% for opcao in pergunta.opcao_set.all%}
                <li>{{opcao.texto}}" = {{ opcao.votos }}
                voto{{ opcao.votos | pluralize}}</li>
            {% endfor %}
        </ul>
        <hr>
        <a href="{% url 'polls:detalhes' pergunta.id %}">Deseja votar novamente?</a> |
        <a href="{% url 'polls:index' %}">Retornar à página principal</a>
    </body>
</html>